# This file is automatically generated by pyo3_stub_gen

import decimal
import typing

from nautilus_trader import model

__all__ = [
    "BestPriceFillModel",
    "CompetitionAwareFillModel",
    "DefaultFillModel",
    "FixedFeeModel",
    "LimitOrderPartialFillModel",
    "MakerTakerFeeModel",
    "MarketHoursFillModel",
    "OneTickSlippageFillModel",
    "PerContractFeeModel",
    "ProbabilisticFillModel",
    "SizeAwareFillModel",
    "StaticLatencyModel",
    "ThreeTierFillModel",
    "TwoTierFillModel",
    "VolumeSensitiveFillModel",
    "adjust_fills_for_partial_window",
    "calculate_reconciliation_price",
    "create_inferred_reconciliation_trade_id",
    "create_position_reconciliation_venue_order_id",
]

@typing.final
class BestPriceFillModel:
    def __init__(
        self, prob_fill_on_limit: float, prob_slippage: float, random_seed: int | None = ...
    ) -> None: ...

@typing.final
class CompetitionAwareFillModel:
    def __init__(
        self,
        prob_fill_on_limit: float = 1.0,
        prob_slippage: float = 0.0,
        random_seed: int | None = None,
        liquidity_factor: float = 0.3,
    ) -> None: ...

@typing.final
class DefaultFillModel:
    def __init__(
        self, prob_fill_on_limit: float, prob_slippage: float, random_seed: int | None = ...
    ) -> None: ...

@typing.final
class FixedFeeModel:
    def __init__(
        self, commission: model.Money, change_commission_once: bool | None = None
    ) -> None: ...

@typing.final
class LimitOrderPartialFillModel:
    def __init__(
        self, prob_fill_on_limit: float, prob_slippage: float, random_seed: int | None = ...
    ) -> None: ...

@typing.final
class MakerTakerFeeModel:
    def __init__(self) -> None: ...

@typing.final
class MarketHoursFillModel:
    def __init__(
        self, prob_fill_on_limit: float, prob_slippage: float, random_seed: int | None = ...
    ) -> None: ...

@typing.final
class OneTickSlippageFillModel:
    def __init__(
        self, prob_fill_on_limit: float, prob_slippage: float, random_seed: int | None = ...
    ) -> None: ...

@typing.final
class PerContractFeeModel:
    def __init__(self, commission: model.Money) -> None: ...

@typing.final
class ProbabilisticFillModel:
    def __init__(
        self, prob_fill_on_limit: float, prob_slippage: float, random_seed: int | None = ...
    ) -> None: ...

@typing.final
class SizeAwareFillModel:
    def __init__(
        self, prob_fill_on_limit: float, prob_slippage: float, random_seed: int | None = ...
    ) -> None: ...

@typing.final
class StaticLatencyModel:
    def __init__(
        self,
        base_latency_nanos: int = 0,
        insert_latency_nanos: int = 0,
        update_latency_nanos: int = 0,
        cancel_latency_nanos: int = 0,
    ) -> None: ...

@typing.final
class ThreeTierFillModel:
    def __init__(
        self, prob_fill_on_limit: float, prob_slippage: float, random_seed: int | None = ...
    ) -> None: ...

@typing.final
class TwoTierFillModel:
    def __init__(
        self, prob_fill_on_limit: float, prob_slippage: float, random_seed: int | None = ...
    ) -> None: ...

@typing.final
class VolumeSensitiveFillModel:
    def __init__(
        self, prob_fill_on_limit: float, prob_slippage: float, random_seed: int | None = ...
    ) -> None: ...

def adjust_fills_for_partial_window(
    mass_status: typing.Any, instrument: typing.Any, tolerance: str | None = None
) -> tuple: ...
def calculate_reconciliation_price(
    current_position_qty: decimal.Decimal,
    current_position_avg_px: decimal.Decimal | None,
    target_position_qty: decimal.Decimal,
    target_position_avg_px: decimal.Decimal | None = ...,
) -> decimal.Decimal | None: ...
def create_inferred_reconciliation_trade_id(
    account_id: model.AccountId,
    instrument_id: model.InstrumentId,
    client_order_id: model.ClientOrderId,
    venue_order_id: model.VenueOrderId | None,
    order_side: model.OrderSide,
    order_type: model.OrderType,
    filled_qty: model.Quantity,
    last_qty: model.Quantity,
    last_px: model.Price,
    position_id: model.PositionId,
    ts_last: int,
) -> model.TradeId: ...
def create_position_reconciliation_venue_order_id(
    account_id: model.AccountId,
    instrument_id: model.InstrumentId,
    order_side: model.OrderSide,
    order_type: model.OrderType,
    quantity: model.Quantity,
    price: model.Price | None = ...,
    venue_position_id: model.PositionId | None = ...,
    ts_last: int = ...,
    tag: str | None = ...,
) -> model.VenueOrderId: ...
